# Generated by Django 4.0.3 on 2022-04-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('날짜', models.TextField(blank=True, null=True)),
                ('알루미늄', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_al',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyDomesticOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('날짜', models.TextField(blank=True, null=True)),
                ('고급휘발유', models.FloatField(blank=True, null=True)),
                ('보통휘발유', models.FloatField(blank=True, null=True)),
                ('자동차용경유', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_domestic_oil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyGrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('날짜', models.TextField(blank=True, null=True)),
                ('대두', models.FloatField(blank=True, null=True)),
                ('밀', models.FloatField(blank=True, null=True)),
                ('옥수수', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_grain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyOverseaOil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('날짜', models.TextField(blank=True, null=True)),
                ('휘발유_95ron', models.FloatField(blank=True, db_column='휘발유_95RON', null=True)),
                ('휘발유_92ron', models.FloatField(blank=True, db_column='휘발유_92RON', null=True)),
                ('경유0001', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'monthly_oversea_oil',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
    ]
